### ISSUE TITLE
【新蛋科技】Web前端开发工程师

### ISSUE THREAD

**Issue by hstarorg** [chengdujs/JobOffers#1]
**岗位职责：**

1. 前端公共组件库的开发，配合架构师完成网站前端的重构；
2. 深入分析和解决前端的各种技术、性能、兼容性问题。
3. 基于react native完成前端功能界面开发（android App，ios App， responsive site）

**任职要求：**

1. 熟悉HTML/CSS，熟练掌握原生Javascript，熟悉ES6，具备响应式UI框架经验（如：Bootstrap）；
2. 一年以上Node开发经验，有React、React Native，Angular.js开发经验尤佳；
3. 熟悉webpack/gulp等工具，有使用经验；
4. 至少熟悉一门后端语言

**加分项：**
1. Github活跃用户
2. React Native 
3. Redux
4. 移动开发经验

**有兴趣，请在成都前端交流群（群号：206731784）中私聊 `成都☆幻~精灵`，或直接留言。简历可以直接发邮箱：jay.m.hu@newegg.com**

**薪资：9-12**

**2017-10-20 17:46:20更新**：需要中高级。

**Comment by zimv** [comment]
哎哟 不错噢

**Comment by 13145209391** [comment]
哎哟 可以哦
